# Generated by Django 3.2.13 on 2022-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[{'1', '신용카드'}], max_length=4, verbose_name='결제방식'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[{'1', '결제'}, {'0', '미결제'}], default='0', max_length=3, verbose_name='결제상태'),
        ),
    ]
