# Generated by Django 3.2.13 on 2022-11-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0002_auto_20221102_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[{2, '결제완료'}, {1, '결제대기'}, {0, '결제취소'}], default=1, max_length=4),
        ),
    ]
