# Generated by Django 3.2.13 on 2022-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0002_auto_20221109_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='list',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='list',
        ),
        migrations.AddField(
            model_name='highlight',
            name='content_location',
            field=models.JSONField(default=dict, verbose_name='컨텐츠위치'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='content_text',
            field=models.TextField(default=1, verbose_name='컨텐츠문구'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='site',
            field=models.ManyToManyField(to='pocket.Site', verbose_name='리스트'),
        ),
    ]
