# Generated by Django 3.2.13 on 2022-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='authentication_check',
            field=models.IntegerField(choices=[{1, '인증'}, {0, '미인증'}], default=0, verbose_name='이메일 인증 여부'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[{1, '신용카드'}], verbose_name='결제방식'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[{2, '결제완료'}, {1, '결제대기'}, {0, '결제취소'}], default=1, verbose_name='결제상태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_status',
            field=models.IntegerField(choices=[{1, '결제'}, {0, '미결제'}], default=0, verbose_name='결제상태'),
        ),
    ]
