# Generated by Django 3.2.13 on 2022-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0004_auto_20221202_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='content_location',
            field=models.JSONField(default=dict, null=True, verbose_name='컨텐츠위치'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='content_text',
            field=models.TextField(null=True, verbose_name='컨텐츠문구'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blog_url',
            field=models.CharField(max_length=250, null=True, verbose_name='블로그url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.TextField(max_length=200, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, unique=True, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_status',
            field=models.IntegerField(choices=[{1, '결제'}, {0, '미결제'}], default=0, null=True, verbose_name='결제상태'),
        ),
    ]
