# Generated by Django 3.2.13 on 2022-11-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0005_auto_20221102_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=156, verbose_name='specific_id')),
                ('horizon_width', models.CharField(max_length=100, verbose_name='horizon_width')),
                ('vertical_width', models.CharField(max_length=100, verbose_name='vertical_width')),
                ('x_location', models.CharField(max_length=100, verbose_name='x_location')),
                ('y_location', models.CharField(max_length=100, verbose_name='y_location')),
            ],
            options={
                'verbose_name': '데이터 목록',
            },
        ),
    ]
