# Generated by Django 3.2.13 on 2022-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0007_auto_20221109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='content',
            field=models.JSONField(default='{}', verbose_name='컨텐츠'),
        ),
    ]
