# Generated by Django 3.2.13 on 2022-11-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0010_alter_highlight_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='content_text',
            field=models.TextField(default=1, verbose_name='하이라이트문구'),
            preserve_default=False,
        ),
    ]
