# Generated by Django 3.2.13 on 2022-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0011_highlight_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='content',
            field=models.JSONField(default=dict, verbose_name='컨텐츠'),
        ),
    ]
