# Generated by Django 3.2.13 on 2022-11-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0012_alter_highlight_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='content',
            new_name='content_location',
        ),
    ]
